export const electricityPriceServiceData = `
<Publication_MarketDocument xmlns="urn:iec62325.351:tc57wg16:451-3:publicationdocument:7:0">
<mRID>6b2c2b067c624ba286770e1040690bbf</mRID>
<revisionNumber>1</revisionNumber>
<type>A44</type>
<sender_MarketParticipant.mRID codingScheme="A01">10X1001A1001A450</sender_MarketParticipant.mRID>
<sender_MarketParticipant.marketRole.type>A32</sender_MarketParticipant.marketRole.type>
<receiver_MarketParticipant.mRID codingScheme="A01">10X1001A1001A450</receiver_MarketParticipant.mRID>
<receiver_MarketParticipant.marketRole.type>A33</receiver_MarketParticipant.marketRole.type>
<createdDateTime>2022-12-16T18:16:25Z</createdDateTime>
<period.timeInterval>
<start>2022-12-14T23:00Z</start>
<end>2022-12-17T23:00Z</end>
</period.timeInterval>
<TimeSeries>
<mRID>1</mRID>
<businessType>A62</businessType>
<in_Domain.mRID codingScheme="A01">10YFI-1--------U</in_Domain.mRID>
<out_Domain.mRID codingScheme="A01">10YFI-1--------U</out_Domain.mRID>
<currency_Unit.name>EUR</currency_Unit.name>
<price_Measure_Unit.name>MWH</price_Measure_Unit.name>
<curveType>A01</curveType>
<Period>
<timeInterval>
<start>2022-12-14T23:00Z</start>
<end>2022-12-15T23:00Z</end>
</timeInterval>
<resolution>PT60M</resolution>
<Point>
<position>1</position>
<price.amount>300.00</price.amount>
</Point>
<Point>
<position>2</position>
<price.amount>290.74</price.amount>
</Point>
<Point>
<position>3</position>
<price.amount>279.46</price.amount>
</Point>
<Point>
<position>4</position>
<price.amount>270.19</price.amount>
</Point>
<Point>
<position>5</position>
<price.amount>274.14</price.amount>
</Point>
<Point>
<position>6</position>
<price.amount>289.87</price.amount>
</Point>
<Point>
<position>7</position>
<price.amount>338.54</price.amount>
</Point>
<Point>
<position>8</position>
<price.amount>439.05</price.amount>
</Point>
<Point>
<position>9</position>
<price.amount>490.03</price.amount>
</Point>
<Point>
<position>10</position>
<price.amount>489.66</price.amount>
</Point>
<Point>
<position>11</position>
<price.amount>474.55</price.amount>
</Point>
<Point>
<position>12</position>
<price.amount>452.75</price.amount>
</Point>
<Point>
<position>13</position>
<price.amount>410.19</price.amount>
</Point>
<Point>
<position>14</position>
<price.amount>396.53</price.amount>
</Point>
<Point>
<position>15</position>
<price.amount>455.05</price.amount>
</Point>
<Point>
<position>16</position>
<price.amount>469.93</price.amount>
</Point>
<Point>
<position>17</position>
<price.amount>485.03</price.amount>
</Point>
<Point>
<position>18</position>
<price.amount>500.00</price.amount>
</Point>
<Point>
<position>19</position>
<price.amount>499.91</price.amount>
</Point>
<Point>
<position>20</position>
<price.amount>485.53</price.amount>
</Point>
<Point>
<position>21</position>
<price.amount>439.90</price.amount>
</Point>
<Point>
<position>22</position>
<price.amount>367.72</price.amount>
</Point>
<Point>
<position>23</position>
<price.amount>336.95</price.amount>
</Point>
<Point>
<position>24</position>
<price.amount>305.39</price.amount>
</Point>
</Period>
</TimeSeries>
<TimeSeries>
<mRID>2</mRID>
<businessType>A62</businessType>
<in_Domain.mRID codingScheme="A01">10YFI-1--------U</in_Domain.mRID>
<out_Domain.mRID codingScheme="A01">10YFI-1--------U</out_Domain.mRID>
<currency_Unit.name>EUR</currency_Unit.name>
<price_Measure_Unit.name>MWH</price_Measure_Unit.name>
<curveType>A01</curveType>
<Period>
<timeInterval>
<start>2022-12-15T23:00Z</start>
<end>2022-12-16T23:00Z</end>
</timeInterval>
<resolution>PT60M</resolution>
<Point>
<position>1</position>
<price.amount>296.30</price.amount>
</Point>
<Point>
<position>2</position>
<price.amount>288.12</price.amount>
</Point>
<Point>
<position>3</position>
<price.amount>280.19</price.amount>
</Point>
<Point>
<position>4</position>
<price.amount>270.33</price.amount>
</Point>
<Point>
<position>5</position>
<price.amount>282.55</price.amount>
</Point>
<Point>
<position>6</position>
<price.amount>296.35</price.amount>
</Point>
<Point>
<position>7</position>
<price.amount>347.59</price.amount>
</Point>
<Point>
<position>8</position>
<price.amount>470.22</price.amount>
</Point>
<Point>
<position>9</position>
<price.amount>543.49</price.amount>
</Point>
<Point>
<position>10</position>
<price.amount>565.01</price.amount>
</Point>
<Point>
<position>11</position>
<price.amount>546.80</price.amount>
</Point>
<Point>
<position>12</position>
<price.amount>547.42</price.amount>
</Point>
<Point>
<position>13</position>
<price.amount>498.13</price.amount>
</Point>
<Point>
<position>14</position>
<price.amount>474.33</price.amount>
</Point>
<Point>
<position>15</position>
<price.amount>467.71</price.amount>
</Point>
<Point>
<position>16</position>
<price.amount>465.14</price.amount>
</Point>
<Point>
<position>17</position>
<price.amount>478.55</price.amount>
</Point>
<Point>
<position>18</position>
<price.amount>449.82</price.amount>
</Point>
<Point>
<position>19</position>
<price.amount>429.10</price.amount>
</Point>
<Point>
<position>20</position>
<price.amount>467.80</price.amount>
</Point>
<Point>
<position>21</position>
<price.amount>305.31</price.amount>
</Point>
<Point>
<position>22</position>
<price.amount>299.91</price.amount>
</Point>
<Point>
<position>23</position>
<price.amount>240.00</price.amount>
</Point>
<Point>
<position>24</position>
<price.amount>104.83</price.amount>
</Point>
</Period>
</TimeSeries>
<TimeSeries>
<mRID>3</mRID>
<businessType>A62</businessType>
<in_Domain.mRID codingScheme="A01">10YFI-1--------U</in_Domain.mRID>
<out_Domain.mRID codingScheme="A01">10YFI-1--------U</out_Domain.mRID>
<currency_Unit.name>EUR</currency_Unit.name>
<price_Measure_Unit.name>MWH</price_Measure_Unit.name>
<curveType>A01</curveType>
<Period>
<timeInterval>
<start>2022-12-16T23:00Z</start>
<end>2022-12-17T23:00Z</end>
</timeInterval>
<resolution>PT60M</resolution>
<Point>
<position>1</position>
<price.amount>200.00</price.amount>
</Point>
<Point>
<position>2</position>
<price.amount>170.00</price.amount>
</Point>
<Point>
<position>3</position>
<price.amount>125.59</price.amount>
</Point>
<Point>
<position>4</position>
<price.amount>128.72</price.amount>
</Point>
<Point>
<position>5</position>
<price.amount>170.01</price.amount>
</Point>
<Point>
<position>6</position>
<price.amount>199.87</price.amount>
</Point>
<Point>
<position>7</position>
<price.amount>170.00</price.amount>
</Point>
<Point>
<position>8</position>
<price.amount>210.01</price.amount>
</Point>
<Point>
<position>9</position>
<price.amount>199.53</price.amount>
</Point>
<Point>
<position>10</position>
<price.amount>201.32</price.amount>
</Point>
<Point>
<position>11</position>
<price.amount>184.36</price.amount>
</Point>
<Point>
<position>12</position>
<price.amount>170.01</price.amount>
</Point>
<Point>
<position>13</position>
<price.amount>205.01</price.amount>
</Point>
<Point>
<position>14</position>
<price.amount>239.99</price.amount>
</Point>
<Point>
<position>15</position>
<price.amount>249.97</price.amount>
</Point>
<Point>
<position>16</position>
<price.amount>252.95</price.amount>
</Point>
<Point>
<position>17</position>
<price.amount>266.86</price.amount>
</Point>
<Point>
<position>18</position>
<price.amount>263.33</price.amount>
</Point>
<Point>
<position>19</position>
<price.amount>251.21</price.amount>
</Point>
<Point>
<position>20</position>
<price.amount>242.00</price.amount>
</Point>
<Point>
<position>21</position>
<price.amount>231.11</price.amount>
</Point>
<Point>
<position>22</position>
<price.amount>229.99</price.amount>
</Point>
<Point>
<position>23</position>
<price.amount>197.72</price.amount>
</Point>
<Point>
<position>24</position>
<price.amount>184.06</price.amount>
</Point>
</Period>
</TimeSeries>
</Publication_MarketDocument>`;
